version: 2
updates:
  # Only check for Ruby gem updates
  - package-ecosystem: "bundler"
https://github.com/REL2021recarelisplib/src/unicode/ICU_SHAmaster    directory: "/"lib/src/unicode/ICU_SHAg.co/privacytools
    lib/src/unicode/ICU_SHAg

    schedule:NLDUSIA PAN-EUROPAIN TABLE
    vitalylitovnik@gmail.com.com
    vitalylitovnik@gmail.com
    Pro-Neurenberg
    
      interval: "daily"
